/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_grafica;
import clase_de_dados.Piloto;
import arquivo_de_dados.PilotoDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kai
 */
public class Tabela extends javax.swing.JFrame {
    private static DefaultTableModel Model;
    private static  PilotoDAO DAO;
    /**
     * Creates new form Tabela
     */
    public Tabela() {
        initComponents();
        Model =(DefaultTableModel)jTable2.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BTNarray = new javax.swing.JButton();
        BTNpilha = new javax.swing.JButton();
        BTNfila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Pais", "Idade", "Equipe", "Motor", "Pontos"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        BTNarray.setText("ArrayLS");
        BTNarray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNarrayActionPerformed(evt);
            }
        });

        BTNpilha.setText("Pilha");
        BTNpilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpilhaActionPerformed(evt);
            }
        });

        BTNfila.setText("Fila");
        BTNfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNfilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNpilha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNarray)
                    .addComponent(BTNfila, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNarray)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNpilha)
                        .addGap(18, 18, 18)
                        .addComponent(BTNfila))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNarrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNarrayActionPerformed
        try {
             DAO= new PilotoDAO();
            for(Piloto piloto:DAO.ConsultarTodos()){ 
           
             Model.addRow(new Object[]{piloto.getCodigo(),piloto.getNome(),piloto.getPais(),piloto.getIdade(),piloto.getEquipe(),piloto.getMotor(),piloto.getPontos()});
       
            }
        
        
        
        
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_BTNarrayActionPerformed

    private void BTNpilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpilhaActionPerformed
//        try {
//           DAO=new PilotoDAO();
//            for (Object p:DAO.ExibirListaPilha()) {
//                Piloto pilo = (Piloto)p;
//                 Model.addRow(new Object[]{pilo.getCodigo(),pilo.getNome(),pilo.getPais(),pilo.getIdade(),pilo.getEquipe(),pilo.getMotor(),pilo.getPontos()});
//            }
//        } catch (Exception e) {
//        }

try {
             DAO= new PilotoDAO();
            for(Piloto piloto:DAO.()){ 
           
             Model.addRow(new Object[]{piloto.getCodigo(),piloto.getNome(),piloto.getPais(),piloto.getIdade(),piloto.getEquipe(),piloto.getMotor(),piloto.getPontos()});
       
            }
        
        
        
        
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_BTNpilhaActionPerformed

    private void BTNfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNfilaActionPerformed
         try {
             DAO= new PilotoDAO();
            for(Piloto piloto:DAO.ExibirLista()){ 
           
             Model.addRow(new Object[]{piloto.getCodigo(),piloto.getNome(),piloto.getPais(),piloto.getIdade(),piloto.getEquipe(),piloto.getMotor(),piloto.getPontos()});
       
            }
        
        
        
        
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BTNfilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNarray;
    private javax.swing.JButton BTNfila;
    private javax.swing.JButton BTNpilha;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
